plugins { id 'com.android.application' }

android {
    namespace 'com.kingdom.crush'
    compileSdk 34

    defaultConfig {
        applicationId 'com.kingdom.crush'
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'com.google.android.gms:play-services-ads:22.6.0'
    implementation 'androidx.core:core:1.12.0'
}
